spring.application.name=Rag_Knowledge_Assistant
server.port=8086

# ==========================================
# PostgreSQL + pgvector
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_ecommerce
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# Logging
# ==========================================
logging.level.root=INFO
logging.level.com.hungrycoders.ai_chatbot=INFO
logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.jdbc=WARN
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

# ==========================================
# PgVector
# ==========================================
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1024
spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.schema-name=public

# ==========================================
# CHAT ? OpenAI dependency (pointed at Groq)
# ==========================================
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=openai/gpt-oss-20b
spring.ai.openai.chat.options.temperature=0.5

# Disable OpenAI embedding auto-config → we use Ollama for embeddings
spring.autoconfigure.exclude=org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration

# ==========================================
# EMBEDDING ? Ollama (local)
# ==========================================
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=mxbai-embed-large
spring.ai.ollama.embedding.options.dimensions=1024

# Disable Ollama chat ? we use OpenAI/Groq for that
spring.ai.ollama.chat.enabled=false

gemini.api.key=${GEMINI_API_KEY:mock-gemini-key}
gemini.api.completions.path=/chat/completions
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/openai
gemini.api.model.name= gemini-2.5-flash
